import { apiClient } from './apiClient';

export const tableService = {
  postCity: (body) => apiClient().post(`/db/city/`, body),
  getCity: () => apiClient().get('/db/city'),
  getCityById: (dataId) => apiClient().get(`/db/city/${dataId}`),
  putCityById: (dataId, body) => apiClient().put(`/db/city/${dataId}`, body),
  deleteCityById: (dataId) => apiClient().delete(`/db/city/${dataId}`),
  postPoint: (body) => apiClient().post(`/db/point/`, body),
  getPoint: (options = '') => apiClient().get(`/db/point${options}`),
  getPointById: (dataId) => apiClient().get(`/db/point/${dataId}`),
  putPointById: (dataId, body) => apiClient().put(`/db/point/${dataId}`, body),
  deletePointById: (dataId) => apiClient().delete(`/db/point/${dataId}`),
  postCar: (body) => apiClient().post(`/db/car/`, body),
  getCar: (options = '') => apiClient().get(`/db/car${options}`),
  getCarById: (dataId) => apiClient().get(`/db/car/${dataId}`),
  putCarById: (dataId, body) => apiClient().put(`/db/car/${dataId}`, body),
  deleteCarById: (dataId) => apiClient().delete(`/db/car/${dataId}`),
  postCategory: (body) => apiClient().post(`/db/category/`, body),
  getCategory: () => apiClient().get('/db/category'),
  putCategoryById: (dataId, body) => apiClient().put(`/db/category/${dataId}`, body),
  deleteCategoryById: (dataId) => apiClient().delete(`/db/category/${dataId}`),
  postRate: (body) => apiClient().post(`/db/rate/`, body),
  getRate: (options = '') => apiClient().get(`/db/rate${options}`),
  putRateById: (dataId, body) => apiClient().put(`/db/rate/${dataId}`, body),
  deleteRateById: (dataId) => apiClient().delete(`/db/rate/${dataId}`),
  postRateType: (body) => apiClient().post(`/db/rateType/`, body),
  getRateType: () => apiClient().get('/db/rateType'),
  putRateTypeById: (dataId, body) => apiClient().put(`/db/rateType/${dataId}`, body),
  deleteRateTypeById: (dataId) => apiClient().delete(`/db/rateType/${dataId}`),
  postOrder: (body) => apiClient().post('/db/order/', body),
  getOrder: (options = '', param = {}) => apiClient().get(`/db/order${options}`, param),
  getOrderById: (orderId) => apiClient().get(`/db/order/${orderId}`),
  postOrderStatus: (body) => apiClient().post(`/db/orderStatus/`, body),
  getOrderStatus: () => apiClient().get(`/db/orderStatus`),
  putOrderStatusById: (dataId, body) => apiClient().put(`/db/orderStatus/${dataId}`, body),
  deleteOrderStatusById: (dataId) => apiClient().delete(`/db/orderStatus/${dataId}`),
};
